### ISSUE TITLE
Dont think this works

### ISSUE THREAD

**Issue by PhanaticD** [macjuul/CHFiles#3]
```
>list_files
[02:03:24 INFO]: CH: Running original command from a MCCommandSender ----> /list_files
[02:03:24 INFO]: An unexpected exception occured during the execution of a script.
[02:03:24 WARN]: java.lang.NoSuchMethodError: com.laytonsmith.core.constructs.CArray.push(Lcom/laytonsmith/core/constructs/Construct;)V
[02:03:24 WARN]:        at me.macjuul.chfiles.functions.functions$list_files.exec(functions.java:464)
[02:03:24 WARN]:        at com.laytonsmith.core.Script.eval(Script.java:375)
[02:03:24 WARN]:        at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1995)
[02:03:24 WARN]:        at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1952)
[02:03:24 WARN]:        at com.laytonsmith.core.Script.run(Script.java:207)
[02:03:24 WARN]:        at com.laytonsmith.core.AliasCore.alias(AliasCore.java:153)
[02:03:24 WARN]:        at com.laytonsmith.commandhelper.CommandHelperServerListener.onServerCommand(CommandHelperServerListener.java:39)
[02:03:24 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor39.execute(Unknown Source)
[02:03:24 WARN]:        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[02:03:24 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[02:03:24 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:03:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[02:03:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[02:03:24 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:436)
[02:03:24 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:404)
[02:03:24 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[02:03:24 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[02:03:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
```
```
/list_files = list_files('/')
```

**Comment by macjuul** [comment]
Released a new version that should fix the issue
https://github.com/macjuul/CHFiles/releases/tag/v1.0.4

If it still doesn't work, re-open the issue with a new comment
